function getContactsPage() {
    return '<div class="content" align=center>\
    <center>\
        <p>Контакты Контент</p>\
    </center>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> 1234556555555555555555werqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> kkkkkkkkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> lllllllllllllllllllllwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> ghhhhhhhhhhhhhhhhhhhhhhhhhwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> 333333333333333333333333333333333wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> 44444444444444444444444444444444444444wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> 55555555555555555555555555555555555555555555555wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> 666666666666666666666666666666666666666666wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> 1234556555555555555555werqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> kkkkkkkkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> lllllllllllllllllllllwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> ghhhhhhhhhhhhhhhhhhhhhhhhhwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> qwqweqerqwerqwerwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> 333333333333333333333333333333333wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> 44444444444444444444444444444444444444wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> 55555555555555555555555555555555555555555555555wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
    <div> 666666666666666666666666666666666666666666wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</div>\
</div>';
}